Fix URLs, use HTTP POST, remove isinstance checks. (#2)
* Fix TypeError. isinstance() needs class instead of module.

Error that it fixes.

    In [1]: import StringIO

    In [2]: isinstance("foo", (file, StringIO))
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-2-c24d9fdf4b90> in <module>()
    ----> 1 isinstance("foo", (file, StringIO))

    TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

    In [3]: isinstance("foo", (file, StringIO.StringIO))
    Out[3]: False

* Bulk create contacts requires HTTP POST instead of PUT.

See https://developer.dotmailer.com/docs/bulk-create-contacts-in-address-book

* Need to call getvalue() on StringIO object. Simplify by removing all this code.

To keep things simple just pass filedata directly into the post method.

* Correct bulk_create_in_address_book() url.

url = '/v2/address-book/{}/contacts/imports'.format(address_book.id)

`address-book` need an `s` on the end.

`imports` needed the `s` removed

* Correct bulk_create() url.

url = '{}/imports'.format(cls.end_point)

`imports` needed `s` removed