Fix TypeError. isinstance() needs class instead of module.
Error that it fixes.

    In [1]: import StringIO

    In [2]: isinstance("foo", (file, StringIO))
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-2-c24d9fdf4b90> in <module>()
    ----> 1 isinstance("foo", (file, StringIO))

    TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

    In [3]: isinstance("foo", (file, StringIO.StringIO))
    Out[3]: False